 		
  		var billDatasArr=[
  		{
  			yearIndex:2015,
  			yearDatas:[
	  			{
	  				monthIndex:1,
	  				monthstatus:0,
	  				monthMoney:1323,
	  				monthDatas:[
		  				{name:'物业管理费：',money:'100.00',status:'1',check:true},
						{name:'水费：',money:'203.20',status:'1',check:true},
						{name:'电费：',money:'20.20',status:'1',check:true},
						{name:'电费：',money:'20.20',status:'1',check:true},
						{name:'保护费：',money:'10.00',status:'1',check:true}
	  				]
	  			},
	  			{
	  				monthIndex:2,
	  				monthstatus:0,
	  				monthMoney:2323,
	  				monthDatas:[
		  				{name:'物业管理费：',money:'100.00',status:'1',check:true},
		  				{name:'物业管理费：',money:'100.00',status:'1',check:true},
		  				{name:'物业管理费：',money:'100.00',status:'1',check:true},
						{name:'水费：',money:'203.20',status:'1',check:true},
						{name:'电费：',money:'20.20',status:'1',check:true},
						{name:'保护费：',money:'10.00',status:'1',check:true}
	  				]
	  			},
	  			{
	  				monthIndex:3,
	  				monthstatus:0,
	  				monthMoney:3323,
	  				monthDatas:[
		  				{name:'物业管理费：',money:'100.00',status:'1',check:true},
						{name:'水费：',money:'203.20',status:'1',check:true},
						{name:'电费：',money:'20.20',status:'1',check:true},
						{name:'保护费保护费：',money:'10.00',status:'1',check:true}
	  				]
	  			},
	  			{
	  				monthIndex:4,
	  				monthstatus:0,
	  				monthMoney:4323,
	  				monthDatas:[
		  				{name:'物业管理费：',money:'100.00',status:'1',check:true},
						{name:'水费：',money:'203.20',status:'1',check:false},
						{name:'电费：',money:'20.20',status:'1',check:true},
						{name:'保护费：',money:'10.00',status:'1',check:true}
	  				]
	  			}
  			]
  		},
  		{
  			yearIndex:2016,
  			yearDatas:[
	  			{
	  				monthIndex:12,
	  				monthstatus:1,
	  				monthMoney:26323,
	  				monthDatas:[
		  				{name:'物业管理费：',money:'100.00',status:'0',check:true},
		  				{name:'物业管理费：',money:'100.00',status:'0',check:true},
		  				{name:'物业管理费：',money:'100.00',status:'0',check:true},
						{name:'水费：',money:'203.20',status:'0',check:true},
						{name:'电费：',money:'20.20',status:'0',check:true},
						{name:'保护费：',money:'10.00',status:'0',check:true}
	  				]
	  			},
	  			{
	  				monthIndex:11,
	  				monthMoney:263,
	  				monthstatus:2,
	  				monthDatas:[
		  				{name:'物业管理费：',money:'100.00',status:'0',check:true},
						{name:'水费：',money:'203.20',status:'0',check:true},
						{name:'电费：',money:'20.20',status:'1',check:true},
						{name:'保护费：',money:'10.00',status:'1',check:true}
	  				]
	  			},
  			]
  		}
  		];
  		
sessionStorage.setItem('billDatasArrSeession',JSON.stringify(billDatasArr));